### ISSUE TITLE
Mountains trying to be birds. Wrong stacking of mountains.

### ISSUE THREAD

**Issue by jheeffer** [vizabi/mountainchart#10]
http://www.gapminder.org/tools/#_locale_id=en;&state_marker_select@_geo=mex;&_geo=egy;&_geo=afg;;&opacitySelectDim=0.00;;&chart-type=mountain

![image](https://user-images.githubusercontent.com/1596071/27291289-1a7c4cce-5510-11e7-969f-dd488fab69c9.png)

**Comment by angiehjort** [comment]
@jheeffer This is expected since you've turned down opacity of non-selected.
